// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/protobuf/gated.proto

/*
Package gated is a generated protocol buffer package.

It is generated from these files:
	proto/protobuf/gated.proto

It has these top-level messages:
	Session
	Request
	Response
	Broadcast
*/
package gated

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Session struct {
	GateId int32  `protobuf:"varint,1,opt,name=gate_id,json=gateId" json:"gate_id,omitempty"`
	Uid    int64  `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Ip     []byte `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Session) GetGateId() int32 {
	if m != nil {
		return m.GateId
	}
	return 0
}

func (m *Session) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Session) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

// @MessageType(21)
type Request struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Content []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *Request) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// @MessageType(22)
type Response struct {
	Uid     int64  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Response) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// @MessageType(23)
type Broadcast struct {
	Uids    []int64 `protobuf:"varint,1,rep,packed,name=uids" json:"uids,omitempty"`
	Content []byte  `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Broadcast) Reset()                    { *m = Broadcast{} }
func (m *Broadcast) String() string            { return proto.CompactTextString(m) }
func (*Broadcast) ProtoMessage()               {}
func (*Broadcast) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Broadcast) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func (m *Broadcast) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "gate.Session")
	proto.RegisterType((*Request)(nil), "gate.Request")
	proto.RegisterType((*Response)(nil), "gate.Response")
	proto.RegisterType((*Broadcast)(nil), "gate.Broadcast")
}

func init() { proto.RegisterFile("proto/protobuf/gated.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0xb8, 0xd4, 0x70, 0x6d, 0x11, 0xf2, 0x82, 0xc5, 0x42, 0x94, 0x85, 0x4c, 0xa9,
	0x04, 0x12, 0x12, 0x6b, 0xc5, 0x00, 0x12, 0x93, 0xd9, 0x58, 0x50, 0x5a, 0x1f, 0xc5, 0x4b, 0x6c,
	0x72, 0xf6, 0x4b, 0xf1, 0x94, 0xc8, 0x57, 0xa2, 0x4e, 0x5d, 0xac, 0xfb, 0x7c, 0xba, 0xef, 0x3f,
	0x1d, 0xdc, 0xc4, 0x31, 0xa4, 0xb0, 0xe6, 0x77, 0x9b, 0xbf, 0xd6, 0xfb, 0x3e, 0xa1, 0xeb, 0x18,
	0xf5, 0xac, 0x40, 0xf3, 0x0c, 0xea, 0x1d, 0x89, 0x7c, 0x18, 0xf4, 0x35, 0xa8, 0xf2, 0xf5, 0xe9,
	0x9d, 0x11, 0xb5, 0x68, 0xcf, 0xec, 0xbc, 0xe0, 0xab, 0xd3, 0x57, 0x20, 0xb3, 0x77, 0xa6, 0xaa,
	0x45, 0x2b, 0x6d, 0x29, 0xf5, 0x25, 0x54, 0x3e, 0x1a, 0x59, 0x8b, 0x76, 0x69, 0x2b, 0x1f, 0x9b,
	0x37, 0x50, 0x16, 0x7f, 0x32, 0x52, 0xd2, 0x77, 0xa0, 0xe8, 0x20, 0x64, 0xcb, 0xe2, 0x7e, 0xd5,
	0x15, 0x4d, 0xf7, 0x9f, 0x62, 0xa7, 0xae, 0x36, 0xa0, 0x76, 0x61, 0x48, 0x38, 0x24, 0x36, 0x2f,
	0xed, 0x84, 0xcd, 0x23, 0x9c, 0x5b, 0xa4, 0x18, 0x06, 0xc2, 0x29, 0x5b, 0x1c, 0xb3, 0x4f, 0xcf,
	0x3d, 0xc1, 0xc5, 0x66, 0x0c, 0xbd, 0xdb, 0xf5, 0x94, 0xb4, 0x86, 0x59, 0xf6, 0x8e, 0x8c, 0xa8,
	0x65, 0x2b, 0x2d, 0xd7, 0xa7, 0x47, 0x37, 0xb7, 0x2f, 0xf2, 0x63, 0x71, 0x38, 0x16, 0xdf, 0xe8,
	0xb7, 0x5a, 0xed, 0x43, 0xfc, 0xc6, 0xd1, 0xf1, 0xf6, 0x6e, 0x3b, 0xe7, 0xe6, 0xc3, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x92, 0x67, 0x49, 0x54, 0x52, 0x01, 0x00, 0x00,
}
