// Code generated by protoc-gen-gopherd. DO NOT EDIT.
// source: proto/protobuf/gated.proto
package gated

const (
	RequestType   = 21
	ResponseType  = 22
	BroadcastType = 23
)

func (*Request) GetMessageType() int32   { return RequestType }
func (*Response) GetMessageType() int32  { return ResponseType }
func (*Broadcast) GetMessageType() int32 { return BroadcastType }
