// Code generated by protoc-gen-gopherd. DO NOT EDIT.
// source: proto/protobuf/gatepb/gatec.proto
package gatepb

const (
	PingType    = 1
	PongType    = 2
	LoginType   = 3
	LogoutType  = 4
	KickoutType = 5
)

func (*Ping) Type() int32    { return PingType }
func (*Pong) Type() int32    { return PongType }
func (*Login) Type() int32   { return LoginType }
func (*Logout) Type() int32  { return LogoutType }
func (*Kickout) Type() int32 { return KickoutType }
