// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/protobuf/gatepb/gated.proto

package gatepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Session struct {
	GateId int32  `protobuf:"varint,1,opt,name=gate_id,json=gateId" json:"gate_id,omitempty"`
	Uid    int64  `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Ip     []byte `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Session) GetGateId() int32 {
	if m != nil {
		return m.GateId
	}
	return 0
}

func (m *Session) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Session) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

// @Type(21)
type Request struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Content []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Request) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *Request) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// @Type(22)
type Response struct {
	Uid     int64  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Response) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Response) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// @Type(23)
type Broadcast struct {
	Uids    []int64 `protobuf:"varint,1,rep,packed,name=uids" json:"uids,omitempty"`
	Content []byte  `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Broadcast) Reset()                    { *m = Broadcast{} }
func (m *Broadcast) String() string            { return proto.CompactTextString(m) }
func (*Broadcast) ProtoMessage()               {}
func (*Broadcast) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Broadcast) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func (m *Broadcast) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "gatepb.Session")
	proto.RegisterType((*Request)(nil), "gatepb.Request")
	proto.RegisterType((*Response)(nil), "gatepb.Response")
	proto.RegisterType((*Broadcast)(nil), "gatepb.Broadcast")
}

func init() { proto.RegisterFile("proto/protobuf/gatepb/gated.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0x18, 0x6a, 0x38, 0xa2, 0x82, 0xbc, 0xe0, 0x31, 0xcd, 0x14, 0x96, 0x54, 0x02,
	0x09, 0x89, 0xb5, 0x62, 0x80, 0x85, 0xc1, 0x6c, 0x2c, 0x28, 0xa9, 0x8f, 0xe2, 0x25, 0x36, 0x39,
	0xe7, 0x4f, 0xf1, 0x2b, 0x51, 0xcf, 0x8d, 0x98, 0xb2, 0xd8, 0xe7, 0x77, 0x7e, 0xef, 0xb3, 0x0f,
	0x36, 0x71, 0x0c, 0x29, 0x6c, 0x79, 0xed, 0xa7, 0xaf, 0xed, 0xa1, 0x4b, 0x18, 0x7b, 0xde, 0x5c,
	0xcb, 0xaa, 0x5e, 0x65, 0xad, 0x7e, 0x06, 0xf5, 0x8e, 0x44, 0x3e, 0x0c, 0xfa, 0x16, 0xd4, 0x51,
	0xfc, 0xf4, 0xce, 0x88, 0x4a, 0x34, 0xe7, 0x96, 0xef, 0xbc, 0x3a, 0x7d, 0x03, 0x72, 0xf2, 0xce,
	0x14, 0x95, 0x68, 0xa4, 0x3d, 0x96, 0x7a, 0x0d, 0x85, 0x8f, 0x46, 0x56, 0xa2, 0x29, 0x6d, 0xe1,
	0x63, 0xfd, 0x06, 0xca, 0xe2, 0xcf, 0x84, 0x94, 0xf4, 0x1d, 0x28, 0xca, 0x81, 0x9c, 0x72, 0x75,
	0x7f, 0xdd, 0x66, 0x54, 0x7b, 0xe2, 0xd8, 0xb9, 0xaf, 0x0d, 0xa8, 0x7d, 0x18, 0x12, 0x0e, 0x89,
	0xb3, 0x4b, 0x3b, 0x1f, 0xeb, 0x47, 0xb8, 0xb0, 0x48, 0x31, 0x0c, 0x84, 0x33, 0x5d, 0xfc, 0xd3,
	0x97, 0x7d, 0x4f, 0x70, 0xb9, 0x1b, 0x43, 0xe7, 0xf6, 0x1d, 0x25, 0xad, 0xe1, 0x6c, 0xf2, 0x8e,
	0x8c, 0xa8, 0x64, 0x23, 0x2d, 0xd7, 0xcb, 0xd6, 0xdd, 0xe6, 0x45, 0x7e, 0x94, 0x79, 0x6e, 0xf9,
	0xbd, 0xbf, 0xc5, 0xfa, 0x10, 0xe2, 0x37, 0x8e, 0xee, 0xf4, 0x81, 0x7e, 0xc5, 0xed, 0x87, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0xfc, 0x3d, 0xda, 0x5f, 0x01, 0x00, 0x00,
}
