// Code generated by protoc-gen-gopherd. DO NOT EDIT.
// source: proto/protobuf/gatepb/gated.proto
package gatepb

import registry "github.com/gopherd/doge/proto"

const (
	RequestType   = 21
	ResponseType  = 22
	BroadcastType = 23
)

func init() {
	registry.Register("gatepb", RequestType, func() registry.Message { return new(Request) })
	registry.Register("gatepb", ResponseType, func() registry.Message { return new(Response) })
	registry.Register("gatepb", BroadcastType, func() registry.Message { return new(Broadcast) })
}

func (*Request) Type() registry.Type   { return RequestType }
func (*Response) Type() registry.Type  { return ResponseType }
func (*Broadcast) Type() registry.Type { return BroadcastType }
