// Code generated by protoc-gen-gopherd. DO NOT EDIT.
// source: proto/protobuf/gatepb/gatec.proto
package gatepb

import registry "github.com/gopherd/doge/proto"
import proto "google.golang.org/protobuf/proto"

var _ = proto.Marshal

const (
	ErrorType     = 130
	PingType      = 131
	PongType      = 132
	LoginReqType  = 133
	LogoutReqType = 134
	LogoutResType = 135
)

func init() {
	registry.Register("gatepb", ErrorType, func() registry.Message { return new(Error) })
	registry.Register("gatepb", PingType, func() registry.Message { return new(Ping) })
	registry.Register("gatepb", PongType, func() registry.Message { return new(Pong) })
	registry.Register("gatepb", LoginReqType, func() registry.Message { return new(LoginReq) })
	registry.Register("gatepb", LogoutReqType, func() registry.Message { return new(LogoutReq) })
	registry.Register("gatepb", LogoutResType, func() registry.Message { return new(LogoutRes) })
}

func (*Error) Typeof() registry.Type        { return ErrorType }
func (m *Error) Sizeof() int                { return proto.Size(m) }
func (m *Error) Nameof() string             { return string(proto.MessageName(m)) }
func (m *Error) Unmarshal(buf []byte) error { return proto.Unmarshal(buf, m) }
func (m *Error) MarshalAppend(buf []byte, useCachedSize bool) ([]byte, error) {
	return proto.MarshalOptions{UseCachedSize: useCachedSize}.MarshalAppend(buf, m)
}

func (*Ping) Typeof() registry.Type        { return PingType }
func (m *Ping) Sizeof() int                { return proto.Size(m) }
func (m *Ping) Nameof() string             { return string(proto.MessageName(m)) }
func (m *Ping) Unmarshal(buf []byte) error { return proto.Unmarshal(buf, m) }
func (m *Ping) MarshalAppend(buf []byte, useCachedSize bool) ([]byte, error) {
	return proto.MarshalOptions{UseCachedSize: useCachedSize}.MarshalAppend(buf, m)
}

func (*Pong) Typeof() registry.Type        { return PongType }
func (m *Pong) Sizeof() int                { return proto.Size(m) }
func (m *Pong) Nameof() string             { return string(proto.MessageName(m)) }
func (m *Pong) Unmarshal(buf []byte) error { return proto.Unmarshal(buf, m) }
func (m *Pong) MarshalAppend(buf []byte, useCachedSize bool) ([]byte, error) {
	return proto.MarshalOptions{UseCachedSize: useCachedSize}.MarshalAppend(buf, m)
}

func (*LoginReq) Typeof() registry.Type        { return LoginReqType }
func (m *LoginReq) Sizeof() int                { return proto.Size(m) }
func (m *LoginReq) Nameof() string             { return string(proto.MessageName(m)) }
func (m *LoginReq) Unmarshal(buf []byte) error { return proto.Unmarshal(buf, m) }
func (m *LoginReq) MarshalAppend(buf []byte, useCachedSize bool) ([]byte, error) {
	return proto.MarshalOptions{UseCachedSize: useCachedSize}.MarshalAppend(buf, m)
}

func (*LogoutReq) Typeof() registry.Type        { return LogoutReqType }
func (m *LogoutReq) Sizeof() int                { return proto.Size(m) }
func (m *LogoutReq) Nameof() string             { return string(proto.MessageName(m)) }
func (m *LogoutReq) Unmarshal(buf []byte) error { return proto.Unmarshal(buf, m) }
func (m *LogoutReq) MarshalAppend(buf []byte, useCachedSize bool) ([]byte, error) {
	return proto.MarshalOptions{UseCachedSize: useCachedSize}.MarshalAppend(buf, m)
}

func (*LogoutRes) Typeof() registry.Type        { return LogoutResType }
func (m *LogoutRes) Sizeof() int                { return proto.Size(m) }
func (m *LogoutRes) Nameof() string             { return string(proto.MessageName(m)) }
func (m *LogoutRes) Unmarshal(buf []byte) error { return proto.Unmarshal(buf, m) }
func (m *LogoutRes) MarshalAppend(buf []byte, useCachedSize bool) ([]byte, error) {
	return proto.MarshalOptions{UseCachedSize: useCachedSize}.MarshalAppend(buf, m)
}
