// Code generated by protoc-gen-gopherd. DO NOT EDIT.
// source: proto/protobuf/gatepb/gated.proto
package gatepb

import registry "github.com/gopherd/doge/proto"

const (
	ForwardType          = 150
	UnicastType          = 151
	MulticastType        = 152
	BroadcastType        = 153
	KickoutType          = 154
	UserLoginType        = 155
	UserLogoutType       = 156
	RegisterRouterType   = 161
	UnregisterRouterType = 162
)

func init() {
	registry.Register("gatepb", ForwardType, func() registry.Message { return new(Forward) })
	registry.Register("gatepb", UnicastType, func() registry.Message { return new(Unicast) })
	registry.Register("gatepb", MulticastType, func() registry.Message { return new(Multicast) })
	registry.Register("gatepb", BroadcastType, func() registry.Message { return new(Broadcast) })
	registry.Register("gatepb", KickoutType, func() registry.Message { return new(Kickout) })
	registry.Register("gatepb", UserLoginType, func() registry.Message { return new(UserLogin) })
	registry.Register("gatepb", UserLogoutType, func() registry.Message { return new(UserLogout) })
	registry.Register("gatepb", RegisterRouterType, func() registry.Message { return new(RegisterRouter) })
	registry.Register("gatepb", UnregisterRouterType, func() registry.Message { return new(UnregisterRouter) })
}

func (*Forward) Type() registry.Type          { return ForwardType }
func (*Unicast) Type() registry.Type          { return UnicastType }
func (*Multicast) Type() registry.Type        { return MulticastType }
func (*Broadcast) Type() registry.Type        { return BroadcastType }
func (*Kickout) Type() registry.Type          { return KickoutType }
func (*UserLogin) Type() registry.Type        { return UserLoginType }
func (*UserLogout) Type() registry.Type       { return UserLogoutType }
func (*RegisterRouter) Type() registry.Type   { return RegisterRouterType }
func (*UnregisterRouter) Type() registry.Type { return UnregisterRouterType }
