// Code generated by protoc-gen-gopherd. DO NOT EDIT.
// source: proto/protobuf/gatec.proto
package gatec

const (
	PingType    = 1
	PongType    = 2
	LoginType   = 3
	LogoutType  = 4
	KickoutType = 5
)

func (*Ping) GetMessageType() int32    { return PingType }
func (*Pong) GetMessageType() int32    { return PongType }
func (*Login) GetMessageType() int32   { return LoginType }
func (*Logout) GetMessageType() int32  { return LogoutType }
func (*Kickout) GetMessageType() int32 { return KickoutType }
