// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/protobuf/gatec.proto

/*
Package gatec is a generated protocol buffer package.

It is generated from these files:
	proto/protobuf/gatec.proto

It has these top-level messages:
	Header
	Ping
	Pong
	Login
	Logout
	Kickout
*/
package gatec

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Kickout_KickoutReason int32

const (
	Kickout_ServiceClosed      Kickout_KickoutReason = 0
	Kickout_UserLogout         Kickout_KickoutReason = 1
	Kickout_LoginAnotherDevice Kickout_KickoutReason = 2
	Kickout_Frozen             Kickout_KickoutReason = 3
)

var Kickout_KickoutReason_name = map[int32]string{
	0: "ServiceClosed",
	1: "UserLogout",
	2: "LoginAnotherDevice",
	3: "Frozen",
}
var Kickout_KickoutReason_value = map[string]int32{
	"ServiceClosed":      0,
	"UserLogout":         1,
	"LoginAnotherDevice": 2,
	"Frozen":             3,
}

func (x Kickout_KickoutReason) String() string {
	return proto.EnumName(Kickout_KickoutReason_name, int32(x))
}
func (Kickout_KickoutReason) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

// optional message header
type Header struct {
	Version   int32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	RequestId int32 `protobuf:"varint,2,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Header) GetRequestId() int32 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

// @MessageType(1)
type Ping struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Ping) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// @MessageType(2)
type Pong struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Pong) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// @MessageType(3)
type Login struct {
	Token    string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Userdata []byte `protobuf:"bytes,2,opt,name=userdata,proto3" json:"userdata,omitempty"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Login) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Login) GetUserdata() []byte {
	if m != nil {
		return m.Userdata
	}
	return nil
}

// @MessageType(4)
type Logout struct {
}

func (m *Logout) Reset()                    { *m = Logout{} }
func (m *Logout) String() string            { return proto.CompactTextString(m) }
func (*Logout) ProtoMessage()               {}
func (*Logout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// @MessageType(5)
type Kickout struct {
	Reason int32 `protobuf:"varint,1,opt,name=reason" json:"reason,omitempty"`
}

func (m *Kickout) Reset()                    { *m = Kickout{} }
func (m *Kickout) String() string            { return proto.CompactTextString(m) }
func (*Kickout) ProtoMessage()               {}
func (*Kickout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Kickout) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

func init() {
	proto.RegisterType((*Header)(nil), "gate.Header")
	proto.RegisterType((*Ping)(nil), "gate.Ping")
	proto.RegisterType((*Pong)(nil), "gate.Pong")
	proto.RegisterType((*Login)(nil), "gate.Login")
	proto.RegisterType((*Logout)(nil), "gate.Logout")
	proto.RegisterType((*Kickout)(nil), "gate.Kickout")
	proto.RegisterEnum("gate.Kickout_KickoutReason", Kickout_KickoutReason_name, Kickout_KickoutReason_value)
}

func init() { proto.RegisterFile("proto/protobuf/gatec.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0xda, 0xa4, 0xed, 0x68, 0x24, 0x2e, 0x52, 0x42, 0x41, 0x2c, 0x39, 0x79, 0x6a,
	0x0f, 0x9e, 0x3c, 0x56, 0x45, 0x2a, 0xf6, 0x20, 0x11, 0x3d, 0x78, 0x91, 0x34, 0x3b, 0xa6, 0x4b,
	0x65, 0xa7, 0xee, 0x6e, 0x0a, 0xfa, 0x48, 0x3e, 0xa5, 0x64, 0x92, 0xf6, 0xd8, 0xcb, 0xc2, 0x37,
	0xf3, 0xf1, 0xef, 0xee, 0x0f, 0xa3, 0x8d, 0x21, 0x47, 0x53, 0x3e, 0x97, 0xd5, 0xe7, 0xb4, 0xcc,
	0x1d, 0x16, 0x13, 0x46, 0xd1, 0xad, 0x21, 0x9d, 0x41, 0x38, 0xc7, 0x5c, 0xa2, 0x11, 0x09, 0xf4,
	0xb6, 0x68, 0xac, 0x22, 0x9d, 0x78, 0x63, 0xef, 0x2a, 0xc8, 0x76, 0x28, 0x2e, 0x00, 0x0c, 0x7e,
	0x57, 0x68, 0xdd, 0x87, 0x92, 0x89, 0xcf, 0xcb, 0x41, 0x3b, 0x79, 0x94, 0xe9, 0x18, 0xba, 0xcf,
	0x4a, 0x97, 0x75, 0x40, 0x41, 0xda, 0xa1, 0x76, 0x1c, 0x30, 0xc8, 0x76, 0xc8, 0x06, 0x1d, 0x34,
	0x6e, 0x20, 0x58, 0x50, 0xa9, 0xb4, 0x38, 0x87, 0xc0, 0xd1, 0x1a, 0x75, 0x2b, 0x34, 0x20, 0x46,
	0xd0, 0xaf, 0x2c, 0x1a, 0x99, 0xbb, 0x9c, 0xef, 0x3f, 0xc9, 0xf6, 0x9c, 0xf6, 0x21, 0x5c, 0x50,
	0x49, 0x95, 0x4b, 0x7f, 0xa0, 0xf7, 0xa4, 0x8a, 0x35, 0x55, 0x4e, 0x0c, 0x21, 0x34, 0x98, 0xdb,
	0xfd, 0x5f, 0x5a, 0x4a, 0xdf, 0x20, 0x6a, 0x95, 0x8c, 0x07, 0xe2, 0x0c, 0xa2, 0x17, 0x34, 0x5b,
	0x55, 0xe0, 0xdd, 0x17, 0x59, 0x94, 0xf1, 0x91, 0x38, 0x05, 0x78, 0xb5, 0x68, 0x9a, 0xd0, 0xd8,
	0x13, 0x43, 0x10, 0xfc, 0xb6, 0x99, 0x26, 0xb7, 0x42, 0x73, 0x8f, 0xb5, 0x1d, 0xfb, 0x02, 0x20,
	0x7c, 0x30, 0xf4, 0x8b, 0x3a, 0xee, 0xdc, 0x5e, 0xce, 0x3b, 0xef, 0xc7, 0x4d, 0xd9, 0xdc, 0xf1,
	0x9f, 0x1f, 0x95, 0xb4, 0x59, 0xa1, 0x91, 0x13, 0xe6, 0x65, 0xc8, 0xcb, 0xeb, 0xff, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf4, 0x41, 0x7c, 0x44, 0x92, 0x01, 0x00, 0x00,
}
